### ISSUE TITLE
Loading a meta file won't load the corresponding mp4 file

### ISSUE THREAD

**Issue by qdot** [FredTungsten/ScriptPlayer#56] opened 2018-03-30 00:20 UTC
Got this from someone on reddit who saw a post I made about ScriptPlayer:

What I have found is that if I go to File > Open Script, and then select a script that is a .META file, then I get an error message that ScriptPlayer can't find the corresponding .MP4 video file, even though it is there in the same directory as the script, and by exactly the same name it says it can't find. If, on the other hand, I select to load the .MP$ video file, it doesn't have any problem finding and loading the script that goes with the video file, so it's easy to get around the issue, but was annoying for a while when I couldn't figure out why it kept saying a .META file that exists couldn't be found. The .funscript files don't seem to have the same issue, they find the video file associated even when selecting to load a .funscript script file. I'm running on Windows 10 64-bit in case that makes a difference.

**Comment by FredTungsten** [comment] 2018-03-30 04:54
Sounds odd and I can't reproduce it. Might be an older Version.

**Comment by seandudley37774** [comment] 2018-03-30 19:00
Hey Fred..  I was the one who reported this to qdot.  I couldn't figure out how to report the bug directly on GitHub as the bug report page didn't have any such ability as far as I could tell.  I think it might have been because my account was incorrectly "flagged" as soon as I created the account, something which has since been corrected by admin.  Anyway, I have really simplified the problem by naming the files 'test.mp4' and 'test.mp4.meta'.  They are both in a directory listed in the "Paths".  When I tell ScriptPlayer to "Open Script" "test.mp4.meta", it comes back and says, "Loaded test.mp4.meta" on the first line, and then the line below it says, "No video for 'test.mp4.meta' found!".  I believe I am running the latest version of ScriptPlayer, it says it is the latest version when it loads, "You are up-to-date!".  Under version, it says I am running version 1.0.5.  If there is anything I can do you help you replicate the problem, just let me know.

Sean

**Comment by FredTungsten** [comment] 2018-03-30 19:08
Ah, that explains it, I didn't know you were using double extionsions (.mp4.meta) those currently only work one way but I'll add that with the next version. For now, if you want to be able to load them either way, you would have to name them test.mp4 and test.meta.

**Comment by seandudley37774** [comment] 2018-03-30 19:18
Ah...  ok, thanks, Fred.

**Comment by FredTungsten** [comment] 2018-03-30 19:29
Fixed in commit de635b8c3fe218e5b0b94051d81d2b28af044f9e, [Build 1.0.5.113](https://ci.appveyor.com/project/FredTungsten/ScriptPlayer/branch/master/job/ikn7abqa0abqgnbn/artifacts)

**Closed by FredTungsten** 2018-03-30 19:29 UTC
Labels: enhancement, planned-feature

**Comment by seandudley37774** [comment] 2018-03-30 22:21
Awesome.. thanks!  Installed, and works now.
