### ISSUE TITLE
ScriptPlayer hangs when Whirligig is closed

### ISSUE THREAD

**Issue by FredTungsten** [FredTungsten/ScriptPlayer#121] opened 2019-11-21 12:21 UTC
As reported on RTS

**Comment by FredTungsten** [comment] 2019-11-22 10:15
Still can't reproduce this. ScriptPlayer just switches to "Whirligig is not connected" and tries to re-establish the connection - as expected/intended.

**Comment by raser1** [comment] 2019-11-22 14:10
Hi Fred,

I've had this problem before, ScriptPlayer only hangs when you try to close it after closing Whirligig. It doesn't always happen either. You have to let a video play & sync a little bit first.

I believe it's due to a thread not wanting to stop when closing the application. Either the Interrupt or Abort call never returns on the WhirligigTimeSource.

**Comment by raser1** [comment] 2019-11-24 13:42
I did some further debugging and it indeed is the `_clientLoop?.Abort()` call that never returns.

You need the following steps to reproduce:

1. Set a breakpoint on `WhirligigTimeSource.Dispose()`
2. Start ScriptPlayer with debugger attached
3. Enable Whirligig mode
4. Start Whirligig
5. Play video with script
6. Close Whirligig
7. Close ScriptPlayer
8. This is where it freezes because of the never returning Abort call

**Comment by FredTungsten** [comment] 2019-11-26 12:13
I got hung up on the communication with Whirligig itself so I didn't notice this can easily be reproduced by simply setting the player to Whirligig and trying to exit ScriptPlayer - without ever having to connect to Whirligig.

I should check all other TimeSources for the same issue, I reused a lot of code when writing those.

The actual issue was a self-made deadlock in the cleanup logic (calling the Dispatcher of the Thread aborting the communication loop thread 😒). It should be fixed now, but it seems like the newest Whirligig beta broke the timeserver feature again so I can't test it anymore ...

**Comment by raser1** [comment] 2019-12-01 19:49
Great to see that you've found the cause :)

Unfortunately I can confirm that the issue also exists on the other TimeSources. 

As for Whirligig I have the occasional issue where it sends the wrong video path, but otherwise it seems to be working fine for me.

**Closed** 2020-01-04 10:59 UTC
Labels: bug
