### ISSUE TITLE
Zoom Player support

### ISSUE THREAD

**Issue by Net005** [FredTungsten/ScriptPlayer#41] opened 2018-02-07 22:51 UTC
Noticed the MPC-HC support and was wondering if Zoom Player could be added as well, they have a expansive communication API which is fast as well with full documentation listed here:

http://forum.inmatrix.com/index.php?s=b5780df9899adacfe5f9ac1ac68cae64&showtopic=7051

C# implementation example which uses basic telnet command as I couldn't get it to accept basic TCP commands back then, not very clean code but could give you some idea:

https://github.com/Net005/Vorze-PlayerHelper/blob/master/VorzeHelper.cs#L161

**Comment by FredTungsten** [comment] 2018-02-08 14:50
Sure, I'll take a look.

**Comment by Net005** [comment] 2018-02-08 16:15
Awesome, btw something unrelated as I noticed a small bug:

In the current master branch it wouldn't save settings on close because by default NoScriptBehaviour is 0 however that is not defined so will return an error when SaveSettings is called:

https://github.com/FredTungsten/ScriptPlayer/blob/4704108cf782c4f391693593f081b2c2eb8a4ad2/ScriptPlayer/ScriptPlayer/ViewModels/SettingsViewModel.cs#L806

Workaround is to make sure to select a noscript behaviour in the settings window which will have 0 boxes ticked at first (as it can't find match)

**Comment by FredTungsten** [comment] 2018-02-08 16:21
Thanks for pointing that out. Should be fixed now.

**Comment by FredTungsten** [comment] 2018-02-08 17:31
Initial Implementation is done (requires "External TCP Control" to be enabled)

**Comment by Net005** [comment] 2018-02-08 17:48
That was quick, tested and working perfectly thanks 👍 
With Zoom Player there's no risk of overloading their API as well unlike with MPC-HC so there's no need for any additional delays / sleeps later on.

Currently it doesn't seem to remember the last playback mode used, might be bug or as intended but thought I should mention it.

**Comment by FredTungsten** [comment] 2018-02-08 17:50
Currently it's intended, but I might add a "Remember last Playback Mode" setting.

**Comment by Net005** [comment] 2018-02-08 21:59
Seems like it isn't syncing the time to ScriptPlayer when seeking in Zoom Player (time stays the same), during first connection it does this but not afterwards so didn't notice it.
Should this be working in the initial implementation or will it be added later?

**Comment by FredTungsten** [comment] 2018-02-09 14:05
I'll look into it and fix that - there is a command to tell zoomplayer to keep sending timestamp updates, maybe I need to send that more often.

**Comment by FredTungsten** [comment] 2018-02-09 16:15
Hmm ... I coulnd't really reproduce that issue (added a couple of things that *might* help). Could you try again and if the issue persists, give me a step-by-step guide on how to reproduce it?

**Comment by Net005** [comment] 2018-02-09 19:53
Tried to debug a bit in VS but with the current master it throws an error when it tries to connect to Zoom Player:

<img width="1124" alt="threaderror" src="https://user-images.githubusercontent.com/11522289/36047004-1c70901a-0ddb-11e8-8fa6-de64a6b32fb3.PNG">

**Comment by FredTungsten** [comment] 2018-02-09 19:57
Woops, forgot to put that through the dispatcher before pushing the commit ^^
Fixed: 8c7b42d49d4886cbd4df64ecf4f95b85dfcee684

**Comment by Net005** [comment] 2018-02-09 20:58
Found the odd little 'bug' as it turns out the initial commands need a slight delay, 500ms also worked but went with 1000ms to be on the safe side as it's only set during initial connection setup:

https://github.com/Net005/ScriptPlayer/commit/2a6dbb458004335e283b53376e5c21b465251650

That works and keeps it in sync seek, will see if Zoom Player has an API log but best guess is internally there it's receiving the commands too close together resulting in mangled command.
Probably depends on machine / network as well which would explain why it couldn't be reproduced, tested with Zoom Player 14 Max.

Can make a PR or can copy over just let me know what you prefer.

**Comment by FredTungsten** [comment] 2018-02-09 21:15
I prefer PR

**Comment by Net005** [comment] 2018-02-09 21:22
PR created 👍

**Comment by FredTungsten** [comment] 2018-02-09 21:26
And ... it's merged

**Comment by FredTungsten** [comment] 2018-02-24 17:43
I'm closing this issue since the implementation is done, feel free to create new issues and/or PRs.

**Closed by FredTungsten** 2018-02-24 17:43 UTC
Labels: feature-request, planned-feature
