### ISSUE TITLE
random chashes 

### ISSUE THREAD

**Issue by peggum2004** [FredTungsten/ScriptPlayer#168] opened 2020-11-11 07:07 UTC
I am using windows 10 
at least 5 to 6 time a night
i am using version 1.1.1
[Crash.log](https://github.com/FredTungsten/ScriptPlayer/files/5522395/Crash.log)
[ButtplugConnectionError.log](https://github.com/FredTungsten/ScriptPlayer/files/5522396/ButtplugConnectionError.log)

this happens with multiple devices 
let me know if you would like any thing else.

**Comment by peggum2004** [comment] 2020-11-11 07:10
It also creates a wer file for the crashes if there is not enough information in the attached logs

**Comment by FredTungsten** [comment] 2020-11-11 14:52
Looks like a problem with Intiface / Buttplug

**Comment by peggum2004** [comment] 2020-11-11 16:01
i am not sure there. I know buttplug stays up and the devices stay connected when the app crashes. i am also able to use Syncydink without any problems. Looking over the windows log i see similar errors. 

Should i try connect directly? let me know if you need any thing else. 

  
Faulting application name: ScriptPlayer.exe, version: 1.1.1.0, time stamp: 0x5f71b655
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1139, time stamp: 0x6a8e6b97
Exception code: 0xe0434352
Fault offset: 0x00114662
Faulting process id: 0x6d38
Faulting application start time: 0x01d6b73081ead779
Faulting application path: C:\Program Files (x86)\ScriptPlayer\ScriptPlayer.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 37a286e4-0270-4a03-8e33-d50ef03f77e3
Faulting package full name: 
Faulting package-relative application ID: 


Application: ScriptPlayer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Buttplug.Client.Connectors.WebsocketConnector.ButtplugWebsocketConnector+<SendAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Buttplug.Client.ButtplugClient+<SendMessageAsync>d__39.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Buttplug.Client.ButtplugClient+<SendMessageExpectOk>d__43.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Buttplug.Client.ButtplugClient+<SendDeviceMessageAsync>d__38.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Buttplug.Client.ButtplugClientDevice+<SendMessageAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ScriptPlayer.Shared.ButtplugAdapter+<Set>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ScriptPlayer.Shared.ButtplugDevice+<Set>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ScriptPlayer.Shared.Device+<CommandLoop>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by FredTungsten** [comment] 2020-11-11 16:04
All of that happens in the Buttplug Client (external dll), not a lot I can do about that.
If you are using a Fleshlight Launch or The Handy, I'd recommend using the native implementation (connect directly).

**Comment by masonj19** [comment] 2020-11-18 09:32
I'm having a similar issue, possibly related?

What's the problem?: Random crashes
How often does it happen?: Almost every attempt to play a script.
What version are you using and on what OS?: ScriptPlayer Version 1.1.1 on Windows 10
Any other external problems involved?: I haven't been able to identify any external problems. Though sometimes only ScriptPlayer crashes, other times ScriptPlayer and the Intiface Engine both crash.
Steps to reproduce?: Connect to Intiface, start playing a script then wait. It's only a matter of time. Seems to frequently crash when changing scripts too, but never on the load of the first script after starting ScriptPlayer.

[Crash.log](https://github.com/FredTungsten/ScriptPlayer/files/5559054/Crash.log)
[ButtplugConnectionError.log](https://github.com/FredTungsten/ScriptPlayer/files/5559055/ButtplugConnectionError.log)

I've only been able to test this with a single device that requires Intiface to connect.
Hope to get this figured out soon. Thanks

**Comment by peggum2004** [comment] 2020-11-19 07:05
That is just like what I was experiencing. When I use the direct connect to the launch I have no problems. But with that being said i dont have away to connect the keon.

**Comment by FredTungsten** [comment] 2020-11-21 06:39
I've added some error handling around the buttplug client - that should take care of some of the crashes but won't fix the underlying problem (connectivity issues?) - the device will likely disconnect instead.

If you are curious what's happening inside of the application during, you can use [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) to see all debug and error messages.

**Comment by masonj19** [comment] 2020-11-21 19:11
I'm doubtful that this is a hardware connectivity problem as I can use ScriptPlayer without loading a script (just using the patterns and testing options from the right hand panel) and it never disconnects. I have also used the game haptics router and some of my own apps written in python and never had any problems

**Comment by FredTungsten** [comment] 2020-11-25 19:25
@masonj19 @peggum2004 
Above PR should fix that issues (available in latest beta)

https://ci.appveyor.com/project/FredTungsten/scriptplayer/build/job/lsmtb1uo55ab742c/artifacts

**Comment by smartu7** [comment] 2020-11-29 07:34
This PR fixed the crash issue but the device(KIIROO KEON) connection is dsiconnected, is possible to keep the connection and make the device work continuously? Can Scriptplayer connect to KEON directly?

**Comment by FredTungsten** [comment] 2020-11-29 07:51
> This PR fixed the crash issue but the device(KIIROO KEON) connection is disconnected, is possible to keep the connection and make the device work continuously? 

The crash likely was because of the disconnect - as mentioned above, the fix should take care of the crash, not the underlying problem itself (as it is out of my control)

> Can Scriptplayer connect to KEON directly?

No, and I don't plan on integrating it - device support is (almost exclusively) done via Buttplug/Intiface

**Closed** 2021-03-05 14:27 UTC
